import type { ClassificationInput, ClassificationResult } from "../engine/types";

export function buildReportManifest(input: ClassificationInput, result: ClassificationResult) {
  return {
    title: "AI Act Risk Classification Report",
    generatedAt: result.generatedAt,
    assessmentVersion: result.assessmentVersion,
    system: {
      name: input.systemName,
      provider: input.providerName,
      purpose: input.purpose,
      sector: input.sector,
      aiInputs: input.aiInputs,
      aiOutputs: input.aiOutputs,
      outputUsers: input.outputUsers,
      actorRole: input.actorRole,
      systemType: input.systemType,
      scope: input.scope,
      interactionMode: input.interactionMode,
      decisionMode: input.decisionMode,
    },
    decision: {
      tier: result.tier,
      riskTier: result.riskTier,
      reviewStatus: result.reviewStatus,
      scopeStatus: result.scopeStatus,
      aiFunctionUnclear: result.aiFunctionUnclear,
      uncertainty: result.uncertainty,
      confidence: result.confidence,
      confidenceLabel: result.confidenceLabel,
      confidenceExplanation: result.confidenceExplanation,
      legalBasis: result.legalBasis,
      riskBasis: result.riskBasis,
      summary: result.summary,
      mainReason: result.mainReason,
      explanation: result.explanation,
      recommendation: result.recommendation,
    },
    evidence: input.evidenceDocuments.map((doc) => ({
      name: doc.name,
      kind: doc.kind,
      findings: doc.extracted,
    })),
    complianceBundle: {
      checklist: result.checklist,
      conformityWorkflow: result.conformityWorkflow,
      citations: result.citations,
      evidenceWarnings: result.evidenceWarnings,
      modelTests: result.modelTestResults,
      requiredControls: result.requiredControls,
      nextSteps: result.nextSteps,
      whatCouldChange: result.whatCouldChange,
      whatCouldChangeResult: result.whatCouldChangeResult,
      recommendedActions: result.recommendedActions,
      gpaIObligations: result.gpaIObligations,
    },
    review: {
      factsUsed: result.factsUsed,
      selectedSignals: result.selectedSignals,
      inferredSignals: result.inferredSignals,
      rejectedSignals: result.rejectedSignals,
      contradictions: result.contradictions,
      evidenceStatus: result.evidenceStatus,
      missingFacts: result.missingFacts,
      safeguards: result.safeguards,
      ruleResults: result.ruleResults,
      matchedRoutes: result.matchedRoutes,
      rejectedRoutes: result.rejectedRoutes,
      uncertaintyNotes: result.uncertaintyNotes,
      reasoningPath: result.reasoningPath,
      assumptions: result.assumptions,
      informationGaps: result.informationGaps,
      nonAIActFlags: result.nonAIActFlags,
      fieldAudit: result.fieldAudit,
    },
  };
}
