import type { ChecklistItem, ClassificationInput, LegalRule } from "./types";

export const prohibitedPracticeRules: LegalRule[] = [
  {
    id: "manipulation",
    category: "prohibited",
    legalBasis: "Article 5(1)(a)",
    label: "Manipulative or deceptive techniques",
    shortDescription:
      "The system uses hidden persuasion, deception, or similar techniques that materially distort behavior and are likely to cause significant harm.",
    triggerQuestion: "Does the system use hidden persuasion, deception, or dark-pattern style manipulation?",
    examples: ["Hidden pressure on children", "Interface design meant to override informed choice"],
    tags: ["manipulation", "deception", "dark patterns"],
  },
  {
    id: "vulnerableGroups",
    category: "prohibited",
    legalBasis: "Article 5(1)(b)",
    label: "Exploitation of vulnerable groups",
    shortDescription:
      "The system exploits age, disability, or economic vulnerability in a way that materially distorts behavior and causes harm.",
    triggerQuestion: "Does it target vulnerable people in a harmful way?",
    examples: ["Predatory child-facing prompts", "Scoring financially distressed users"],
    tags: ["vulnerability", "children", "exploitation"],
  },
  {
    id: "socialScoring",
    category: "prohibited",
    legalBasis: "Article 5(1)(c)",
    label: "Social scoring",
    shortDescription:
      "The system creates a broad social score or reputation score that leads to unjustified or disproportionate treatment.",
    triggerQuestion: "Does it create a broad social score that affects rights or access?",
    examples: ["Citizen score", "Cross-context reputation score"],
    tags: ["social scoring", "score"],
  },
  {
    id: "criminalRiskSolelyProfiling",
    category: "prohibited",
    legalBasis: "Article 5(1)(d)",
    label: "Criminal-risk prediction based solely on profiling",
    shortDescription:
      "The system predicts a person's risk of offending using profiling, traits, or demographics alone rather than objective facts linked to criminal activity.",
    triggerQuestion: "Does it predict criminal risk only from profiling or demographic traits?",
    examples: ["Predictive policing from address and family links", "Risk score from personal background alone"],
    tags: ["profiling", "law enforcement", "criminal risk"],
  },
  {
    id: "realTimePublicSpaceBiometricIdentification",
    category: "prohibited",
    legalBasis: "Article 5(1)(h)",
    label: "Real-time remote biometric identification in public space",
    shortDescription:
      "The system performs real-time remote biometric identification in publicly accessible spaces for law-enforcement purposes, subject to narrow legal exceptions.",
    triggerQuestion: "Does law enforcement use real-time biometric identification in public space?",
    examples: ["Live facial recognition across a public square", "Real-time identification at a station"],
    tags: ["biometric", "real-time", "public space", "law enforcement"],
  },
  {
    id: "untargetedFacialImageScraping",
    category: "prohibited",
    legalBasis: "Article 5(1)(e)",
    label: "Untargeted scraping of facial images",
    shortDescription:
      "The system scrapes facial images from the internet or other sources to build or expand facial-recognition databases without targeted collection or lawful basis.",
    triggerQuestion: "Does it scrape facial images to build a facial-recognition database?",
    examples: ["Building a face dataset from web photos", "Collecting public profile images at scale"],
    tags: ["facial images", "scraping", "database"],
  },
  {
    id: "workplaceOrEducationEmotionRecognition",
    category: "prohibited",
    legalBasis: "Article 5(1)(f)",
    label: "Emotion recognition in workplace or education",
    shortDescription:
      "The system infers emotions in work or education settings, unless a narrow medical or safety exception clearly applies.",
    triggerQuestion: "Does it infer emotions in a workplace or school setting?",
    examples: ["Student attention scoring", "Employee mood monitoring"],
    tags: ["emotion recognition", "workplace", "education"],
  },
  {
    id: "sensitiveBiometricCategorization",
    category: "prohibited",
    legalBasis: "Article 5(1)(g)",
    label: "Sensitive biometric categorization",
    shortDescription:
      "The system uses biometric data to infer sensitive traits such as race, religion, political opinion, trade-union membership, sex life, or sexual orientation.",
    triggerQuestion: "Does it infer sensitive traits from biometric data?",
    examples: ["Inferring religion from face or tattoos", "Inferring sexual orientation from biometric features"],
    tags: ["biometric categorization", "sensitive data"],
  },
];

export const highRiskRules: LegalRule[] = [
  {
    id: "employment",
    category: "highRisk",
    legalBasis: "Annex III, point 4",
    label: "Employment and worker management",
    shortDescription: "Recruitment screening, promotion, dismissal, task allocation, worker monitoring, or evaluation.",
    triggerQuestion: "Is it used for hiring, recruitment screening, promotion, dismissal, or worker monitoring?",
    examples: ["Applicant screening engine", "Employee performance ranker"],
    tags: ["employment", "hiring", "workers"],
  },
  {
    id: "education",
    category: "highRisk",
    legalBasis: "Annex III, point 3",
    label: "Education and vocational training",
    shortDescription: "Admission, grading, assessment, learning-path decisions, or cheating detection.",
    triggerQuestion: "Is it used for admission, grading, assessment, or learning-path decisions?",
    examples: ["Automated exam scoring", "University admission ranker"],
    tags: ["education", "students"],
  },
  {
    id: "healthcare",
    category: "highRisk",
    legalBasis: "Article 6 and Annex I/III context",
    label: "Healthcare and patient-risk support",
    shortDescription: "Triage, diagnosis, treatment, or patient-risk support where the output can materially affect health decisions or care pathways.",
    triggerQuestion: "Does it support triage, diagnosis, treatment, or patient-risk decisions?",
    examples: ["Clinical triage assistant", "Diagnosis support model"],
    tags: ["healthcare", "medical", "patient"],
  },
  {
    id: "finance",
    category: "highRisk",
    legalBasis: "Annex III, point 5",
    label: "Credit or loan eligibility",
    shortDescription: "Eligibility, pricing, or access decisions for credit or loan-related services.",
    triggerQuestion: "Does it decide or materially influence credit or loan eligibility?",
    examples: ["Loan underwriting support", "Credit scoring engine"],
    tags: ["credit", "loan", "finance"],
  },
  {
    id: "insurance",
    category: "highRisk",
    legalBasis: "Annex III, point 5",
    label: "Insurance eligibility or pricing",
    shortDescription: "Eligibility, pricing, or access decisions for insurance or similar essential financial services where the output affects a person's terms or access.",
    triggerQuestion: "Does it affect insurance eligibility, access, or pricing?",
    examples: ["Insurance risk scoring", "Premium adjustment model"],
    tags: ["insurance", "pricing"],
  },
  {
    id: "publicServices",
    category: "highRisk",
    legalBasis: "Annex III, point 5",
    label: "Essential private or public services",
    shortDescription: "Access, prioritization, or eligibility for essential public services, benefits, or similar services.",
    triggerQuestion: "Does it affect access to essential services, benefits, or public services?",
    examples: ["Benefit eligibility scoring", "Service prioritization model"],
    tags: ["benefits", "public services", "access"],
  },
  {
    id: "migration",
    category: "highRisk",
    legalBasis: "Annex III, point 7",
    label: "Migration, asylum, visa, or border control",
    shortDescription: "Visa, asylum, border, or migration decision support.",
    triggerQuestion: "Is it used for migration, asylum, visa, or border control decisions?",
    examples: ["Visa triage", "Asylum support tool"],
    tags: ["migration", "border", "visa"],
  },
  {
    id: "lawEnforcement",
    category: "highRisk",
    legalBasis: "Annex III, point 6",
    label: "Law enforcement",
    shortDescription: "Risk assessment, evidence analysis, investigative prioritization, or similar law-enforcement support.",
    triggerQuestion: "Is it used by or for law enforcement to assess people, evidence, or risk?",
    examples: ["Evidence analysis assistant", "Recidivism support tool"],
    tags: ["law enforcement", "criminal justice"],
  },
  {
    id: "justice",
    category: "highRisk",
    legalBasis: "Annex III, point 8",
    label: "Justice and democratic processes",
    shortDescription: "Judicial decision support, legal interpretation, voting behavior, or election influence.",
    triggerQuestion: "Does it support judicial decisions, legal interpretation, voting, or election outcomes?",
    examples: ["Judicial recommendation tool", "Election targeting model"],
    tags: ["justice", "courts", "democracy"],
  },
  {
    id: "criticalInfrastructure",
    category: "highRisk",
    legalBasis: "Annex III, point 2",
    label: "Critical infrastructure and safety-critical systems",
    shortDescription: "Safety components in critical infrastructure, regulated products, or other safety-critical systems.",
    triggerQuestion: "Could failure affect critical infrastructure or a safety-critical product or service?",
    examples: ["Grid control AI", "Traffic safety routing"],
    tags: ["infrastructure", "safety", "product safety"],
  },
  {
    id: "productSafety",
    category: "highRisk",
    legalBasis: "Annex I and product-safety context",
    label: "Product-safety decision support",
    shortDescription: "Decision support connected to safety-critical or regulated products can require high scrutiny when it influences release, certification, inspection, or incident handling.",
    triggerQuestion: "Does it support a safety-critical or regulated product decision?",
    examples: ["Safety inspection prioritization", "Regulated device triage support"],
    tags: ["product safety", "regulated product"],
  },
  {
    id: "biometricIdentification",
    category: "highRisk",
    legalBasis: "Annex III, point 1",
    label: "Biometric identification",
    shortDescription: "Remote biometric identification systems that are not already prohibited.",
    triggerQuestion: "Does it identify people through biometric matching outside a prohibited context?",
    examples: ["Post-event facial identification", "Biometric access matching"],
    tags: ["biometric identification", "identity"],
  },
  {
    id: "biometricCategorization",
    category: "highRisk",
    legalBasis: "Annex III, point 1",
    label: "Biometric categorization",
    shortDescription: "Biometric categorization that does not amount to a prohibited sensitive-trait inference.",
    triggerQuestion: "Does it categorize people using biometric data without inferring sensitive traits?",
    examples: ["Age-band estimate for access control", "Fitness category estimate"],
    tags: ["biometrics", "categorization"],
  },
];

export const limitedRiskRules: LegalRule[] = [
  {
    id: "chatbot",
    category: "limitedRisk",
    legalBasis: "Article 50(1)",
    label: "AI interacting directly with people",
    shortDescription: "People should be informed that they are interacting with AI unless that is obvious from context.",
    triggerQuestion: "Does it directly interact with users as a chatbot, assistant, or agent?",
    examples: ["Customer-support chatbot", "AI onboarding assistant"],
    tags: ["chatbot", "notice"],
  },
  {
    id: "deepfake",
    category: "limitedRisk",
    legalBasis: "Article 50(4)",
    label: "Synthetic or manipulated media",
    shortDescription: "AI-generated or AI-manipulated media should be disclosed or labeled when it could appear authentic.",
    triggerQuestion: "Does it generate or manipulate realistic text, image, audio, or video content?",
    examples: ["Synthetic CEO video", "AI-generated marketing image"],
    tags: ["deepfake", "synthetic content"],
  },
  {
    id: "emotionRecognition",
    category: "limitedRisk",
    legalBasis: "Article 50(3)",
    label: "Emotion recognition outside prohibited contexts",
    shortDescription: "Emotion recognition that is not in a prohibited work or education setting still usually needs notice.",
    triggerQuestion: "Does it infer emotions outside a prohibited workplace or education use case?",
    examples: ["Retail sentiment assistant", "Driver-fatigue alert"],
    tags: ["emotion recognition", "notice"],
  },
  {
    id: "generatedContent",
    category: "limitedRisk",
    legalBasis: "Article 50 and GPAI transparency context",
    label: "Public-facing generated content",
    shortDescription: "Public-facing generated content should be marked or disclosed where users could mistake it for human-authored content.",
    triggerQuestion: "Does it generate public-facing content?",
    examples: ["Marketing copy assistant", "Generated product images"],
    tags: ["generative AI", "content"],
  },
];

export const highRiskChecklist: ChecklistItem[] = [
  {
    title: "Risk management system",
    legalBasis: "Article 9",
    description: "Create a process to identify, evaluate, mitigate, and monitor foreseeable risks.",
    priority: "critical",
  },
  {
    title: "Data governance and quality controls",
    legalBasis: "Article 10",
    description: "Document training, validation, and testing data quality, relevance, and bias checks.",
    priority: "critical",
  },
  {
    title: "Technical documentation",
    legalBasis: "Article 11 and Annex IV",
    description: "Document design, intended purpose, logic, performance, limitations, and compliance evidence.",
    priority: "critical",
  },
  {
    title: "Logging and record keeping",
    legalBasis: "Article 12",
    description: "Maintain logs appropriate to the system's purpose and risk profile.",
    priority: "high",
  },
  {
    title: "Transparency and instructions",
    legalBasis: "Article 13",
    description: "Explain capabilities, limitations, and human-oversight needs to deployers.",
    priority: "high",
  },
  {
    title: "Human oversight",
    legalBasis: "Article 14",
    description: "Design meaningful oversight so humans can monitor, intervene, override, or stop the system.",
    priority: "critical",
  },
  {
    title: "Accuracy, robustness, and cybersecurity",
    legalBasis: "Article 15",
    description: "Specify performance metrics and maintain resilience against errors and misuse.",
    priority: "high",
  },
  {
    title: "Post-market monitoring and incident response",
    legalBasis: "Articles 72 and 73",
    description: "Track real-world performance and prepare serious-incident escalation procedures.",
    priority: "medium",
  },
];

export const limitedRiskChecklist: ChecklistItem[] = [
  {
    title: "AI disclosure",
    legalBasis: "Article 50",
    description: "Tell people when they are interacting with AI unless that is obvious from the circumstances.",
    priority: "high",
  },
  {
    title: "Synthetic media label",
    legalBasis: "Article 50",
    description: "Mark generated or manipulated media that could appear authentic.",
    priority: "high",
  },
  {
    title: "Plain-language notice",
    legalBasis: "Article 50",
    description: "Explain what the system does and how people can contact the deployer or provider.",
    priority: "medium",
  },
];

export const minimalRiskChecklist: ChecklistItem[] = [
  {
    title: "AI literacy and governance hygiene",
    legalBasis: "Article 4 and general good practice",
    description: "Train staff on the system's intended use, limits, and escalation points.",
    priority: "medium",
  },
  {
    title: "Short model card",
    legalBasis: "Voluntary good practice",
    description: "Keep a short record of purpose, users, data categories, limitations, and review owner.",
    priority: "medium",
  },
];

export const impactWeight: Record<string, number> = {
  low: -12,
  moderate: -3,
  material: 8,
  critical: 14,
};
